dado = input('Digite algo: ')

print('Foi digitado: {}'.format(dado))
print('Tipo primitivo: ', type(dado))
print('Todos os caracteres ...')
print('... são números ou letras do alfabeto? ', dado.isalnum())
print('... são letras do alfabeto? ', dado.isalpha())
print('... são caracteres ASCII?', dado.isascii())
print('... são dígitos?', dado.isdigit())
print('... estão em minúsculo?', dado.islower())
print('... estão em maiúsculo?', dado.isupper())
print('... são caracteres decimais?', dado.isdecimal())
print('... compõem um identificador válido?', dado.isidentifier())
print('... são numéricos?', dado.isnumeric())
print('... são imprimíveis?', dado.isprintable())
print('... são espaços em branco?', dado.isspace())
print('... estão em minúscula exceto o primeiro? ', dado.istitle())
